[package]
name = "cargopublish"
version = "0.1.0"
authors = ["rahul-thakoor <rahul.thakoor@gmail.com>"]

[dependencies]
cargo-name = "1.0.0"
serde_derive = "1.0"
toml = "0.4"
serde = "1.0"
reqwest = "0.8.6"
serde_json = "1.0.19"
license-exprs = "1.3.0"